# Content source configuration
# Set content_source_type to either "file" or "google_sheet"
content_source_type: "file"  # Change to "google_sheet" to use Google Sheets

# File source configuration (used when content_source_type is "file")
content_csv_path: "src/dat/curated_content.csv"
content_format: "csv"

# Google Sheets configuration (used when content_source_type is "google_sheet")
google_sheet:
  # The ID of the Google Sheet (found in the URL between /d/ and /edit)
  # Example: https://docs.google.com/spreadsheets/d/THIS_IS_THE_ID/edit#gid=0
  sheet_id: "your-google-sheet-id-here"
  
  # Optional: Name of the worksheet to use. If omitted, uses the first sheet
  worksheet_name: "Sheet1"
  
  # Path to the Google service account credentials JSON file
  # Can also be set via GOOGLE_CREDENTIALS_PATH environment variable
  credentials_path: "config/google-credentials.json"

# Scheduling
schedule:
  mode: "interval"  # interval or specific_times
  interval_minutes: 60  # post every 1 hour
  specific_times:  # alternative to interval, ignored if mode is "interval"
    - "09:00"
    - "17:00"
    - "21:00"

# Logging
logging:
  file_path: "src/log/pipeline.log"
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL

