version: '3.8'

services:
  x-scheduler:
    build: .
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      # - ./src/dat:/app/src/dat # Commented out as src/dat seems unused
      - ./config:/app/config # Map config directory
    restart: always