AWSTemplateFormatVersion: '2010-09-09'
Description: >
  CloudFormation template to create the IAM policy required for the x-scheduler application
  to access parameters stored in AWS Systems Manager Parameter Store.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Policy Configuration"
        Parameters:
          - PolicyName
          - AccountId
          - Region
    ParameterLabels:
      PolicyName:
        default: "Name of the IAM policy"
      AccountId:
        default: "AWS Account ID"
      Region:
        default: "AWS Region"

Parameters:
  PolicyName:
    Type: String
    Default: x-scheduler-SSM-Read-Policy
    Description: Name for the IAM policy that will be created
  
  AccountId:
    Type: String
    Default: '164638039016'
    Description: AWS Account ID where the policy will be created
    
  Region:
    Type: String
    Default: us-east-1
    Description: AWS Region where the SSM parameters are stored
    
Resources:
  # IAM Policy for x-scheduler application to read SSM parameters
  XSchedulerSSMReadPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Ref PolicyName
      Description: "Allows reading AWS Systems Manager Parameter Store parameters for the x-scheduler application"
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - ssm:GetParameter
              - ssm:GetParameters
            Resource: !Sub 'arn:aws:ssm:${Region}:${AccountId}:parameter/x-scheduler/*'

Outputs:
  PolicyArn:
    Description: "ARN of the created IAM policy"
    Value: !Ref XSchedulerSSMReadPolicy
    Export:
      Name: !Sub "${AWS::StackName}-PolicyArn"

